"""Removendo transaction type

Revision ID: 3f99b88c01d4
Revises: faaca47d8ed8
Create Date: 2024-11-10 00:16:50.126755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f99b88c01d4'
down_revision: Union[str, None] = 'faaca47d8ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transaction', 'type',
               existing_type=postgresql.ENUM('START', 'INCOME', 'OUTCOME', name='transactiontype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transaction', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('START', 'INCOME', 'OUTCOME', name='transactiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###
