"""fix de relação transactions com categories

Revision ID: 56d0ecc8cce6
Revises: 3f99b88c01d4
Create Date: 2024-11-10 00:28:37.411512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d0ecc8cce6'
down_revision: Union[str, None] = '3f99b88c01d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
