"""Adding unique constraint to transaction

Revision ID: 6b742d2bb525
Revises: 1bcfc370afd2
Create Date: 2025-06-04 13:10:22.410794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b742d2bb525'
down_revision: Union[str, None] = '1bcfc370afd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transactions_unique_entry', 'transactions', ['account_id', 'date', 'description', 'amount'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_unique_entry', 'transactions', type_='unique')
    # ### end Alembic commands ###
