"""Refatoração da tabela Balance e criação da tabela transaction

Revision ID: faaca47d8ed8
Revises: 84c3d7a6d960
Create Date: 2024-11-10 00:00:01.347893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faaca47d8ed8'
down_revision: Union[str, None] = '84c3d7a6d960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('START', 'INCOME', 'OUTCOME', name='transactiontype', create_constraint=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Transaction_id'), 'Transaction', ['id'], unique=False)
    op.drop_constraint('Balance_category_id_fkey', 'Balance', type_='foreignkey')
    op.drop_column('Balance', 'type')
    op.drop_column('Balance', 'description')
    op.drop_column('Balance', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Balance', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Balance', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Balance', sa.Column('type', postgresql.ENUM('START', 'INCOME', 'OUTCOME', name='typetype'), autoincrement=False, nullable=False))
    op.create_foreign_key('Balance_category_id_fkey', 'Balance', 'Categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_Transaction_id'), table_name='Transaction')
    op.drop_table('Transaction')
    # ### end Alembic commands ###
